HOST = 'growingdever.cafe24.com:7778';

RESULT_CODE_FAIL = 0;
RESULT_CODE_SUCCESS = 1;
RESULT_CODE_AUTH_FAIL = 2;
RESULT_CODE_ALREADY_EXIST_USERID = 3;
RESULT_CODE_NOT_FOUND_USERID = 4;
RESULT_CODE_DB_ERROR = 5;
RESULT_CODE_NOT_VALID_ACCESS_TOKEN = 6;
RESULT_CODE_EXPIRED_ACCESS_TOKEN = 7;
RESULT_CODE_ALREADY_EXIST_REQUEST = 8;
RESULT_CODE_NOT_EXIST_REQUEST = 9;
RESULT_CODE_ALREADY_ACCEPTED_REQUEST = 10;
RESULT_CODE_ALREADY_SENT_REQUEST = 11;
RESULT_CODE_INVALID_INPUT = 12;
RESULT_CODE_NOT_FOUND_RELATIONSHIP = 13;

PUSH_MESSAGE_TYPE_REQUEST_UPDATING = 1;
PUSH_MESSAGE_TYPE_REQUEST_RELATIONSHIP = 2;


ERROR_MESSAGE_FAIL_TO_SIGNIN = 'failed to sign in...';