HOST = 'growingdever.cafe24.com:7778';

RESULT_CODE_FAIL = 0;
RESULT_CODE_SUCCESS = 1;
RESULT_CODE_AUTH_FAIL = 2;
RESULT_CODE_ALREADY_EXIST_USERID = 3;
RESULT_CODE_NOT_FOUND_USERID = 4;
RESULT_CODE_DB_ERROR = 5;
RESULT_CODE_NOT_VALID_ACCESS_TOKEN = 6;
RESULT_CODE_EXPIRED_ACCESS_TOKEN = 7;

ERROR_MESSAGE_FAIL_TO_SIGNIN = 'failed to sign in...';